package com.spatialmemory.app.data

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Categorizes the type of spatial change detected between current camera/sensor feed and stored spatial memory.
 */
enum class ChangeEventType {
    /** A new unmapped obstacle or object was detected in the environment. */
    NEW_OBJECT,

    /** An existing mapped landmark object has shifted to a new position. */
    OBJECT_MOVED,

    /** A previously registered landmark object was expected but missing during a scan. */
    OBJECT_MISSING,

    /** A landmark object's orientation, structural state, or open/closed state altered significantly. */
    LANDMARK_ALTERED
}

/**
 * User feedback response for tuning alert thresholds and personalization logic.
 */
enum class UserFeedback {
    /** The user acknowledged the change alert as accurate and helpful. */
    USEFUL,

    /** The user flagged the change alert as false alarm, unhelpful, or redundant noise. */
    NOT_USEFUL
}

/**
 * Entity representing a detected delta or change event in spatial memory.
 *
 * ChangeEvents are generated by the spatial diffing engine when current camera/ARCore scans
 * deviate from baseline landmarks. This log is used both for real-time auditory/haptic alerting
 * and for offline personalized threshold tuning via user feedback.
 *
 * @property id Unique string identifier for the change event.
 * @property placeId Foreign key referencing the parent [Place].
 * @property landmarkId Nullable foreign key referencing the associated [Landmark] (null if [ChangeEventType.NEW_OBJECT]).
 * @property eventType Nature of detected change ([ChangeEventType.NEW_OBJECT], [ChangeEventType.OBJECT_MOVED], [ChangeEventType.OBJECT_MISSING], [ChangeEventType.LANDMARK_ALTERED]).
 * @property severityScore Risk/threat assessment score from 0.0 (negligible) to 1.0 (critical hazard). Calculated based on object permanence class, bounding box height (trip hazard), and proximity to walking corridors.
 * @property detectedAt Epoch timestamp (in milliseconds) when the spatial change was detected.
 * @property userFeedback Feedback status ([UserFeedback.USEFUL], [UserFeedback.NOT_USEFUL], or null by default). Feedback adapts severity calculation thresholds over time for user preference.
 */
@Entity(
    tableName = "change_events",
    foreignKeys = [
        ForeignKey(
            entity = Place::class,
            parentColumns = ["id"],
            childColumns = ["placeId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = Landmark::class,
            parentColumns = ["id"],
            childColumns = ["landmarkId"],
            onDelete = ForeignKey.SET_NULL
        )
    ],
    indices = [
        Index(value = ["placeId"]),
        Index(value = ["landmarkId"])
    ]
)
data class ChangeEvent(
    @PrimaryKey
    val id: String,
    val placeId: String,
    val landmarkId: String?,
    val eventType: ChangeEventType,
    val severityScore: Float,
    val detectedAt: Long,
    val userFeedback: UserFeedback? = null
)
