allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

allprojects {
    tasks.withType(org.gradle.api.tasks.compile.JavaCompile).configureEach {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    tasks.configureEach { task ->
        if (task.name.startsWith("compile") && task.name.endsWith("Kotlin")) {
            try {
                task.kotlinOptions.jvmTarget = "21"
            } catch (Throwable e) {}
        }
    }
}
