allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    tasks.configureEach { task ->
        if (task.name.toLowerCase().contains("kotlin")) {
            try {
                task.kotlinOptions.jvmTarget = "17"
            } catch (Exception e) {
                // Ignore if it's not a KotlinCompile task
            }
        }
    }
}
